### ISSUE TITLE
Bilder not working

### ISSUE THREAD

**Issue by XenSide** [No-Bling/DOTA#1]
After trying to build my own custom .vpk by using the builder and then moving the file from dota_lv to english% it appears that the .vpk is not working (the prebuilt ones you posted do work fine).

**Comment by AveYo** [comment]
Builder script has not been updated after 7.07  
Will be up and running soon (a day or two).

**Comment by AveYo** [comment]
Valve time indeed 👎  
Finally shared v2.0rc
