### ISSUE TITLE
Invisible "Lone Druid - Spirit of Calm Panda"

### ISSUE THREAD

**Issue by ilyasovivan** [No-Bling/DOTA#10]
Bug (full settings) Panda is invisible. And I can't attack it whan use mouse.

**Comment by AveYo** [comment]
Will investigate in a few hours. Thanks for reporting!

**Comment by AveYo** [comment]
Can not confirm issue.   
Both the batch script and the pre-made build ( \_ ) replace the  custom model with the default bear, not invisible model.   
Are you sure you are using the latest version? Just download the whole repository zip again   
If still not ok, provide a bit more details (if using script / pre-made builds, what choices)

**Comment by ilyasovivan** [comment]
The problem was with DirectX 11 (-dx11) and -oldtexturestreaming startup parameter (in windowed mode). I do not recommend using these options together.

**Comment by AveYo** [comment]
yep, `-oldtexturestreaming` is meant for potatoes, hence -dx9
