### ISSUE TITLE
a command not related to the tool

### ISSUE THREAD

**Issue by Fr33domJustice** [No-Bling/DOTA#12]
Hi there, so this was a lil odd, i was using this command in console from very long time ago so now it's still remember in my dota 2, it makes all the hero animations in the game not moving when i finished a game, i don't know how to put it well in words, which is a command i've read somewhere in reddit from you.

It does help my fps stable after each game but now i wanna watch a replay and all the creeps and heroes don't have any animation like in the main menu, they just moving like a stone. So by any chance can you provide me what was the command in console to toggle it.

Thanks in advance

**Comment by AveYo** [comment]
for these kind of unrelated questions is better to contact me on reddit. 

anyway, that old command (`r_dota_disable_portrait_world_renderer 1`) was disabled by valve not long after I made it popular, so maybe you've used another command (`anim_disable 1`) or even my alternative via vscript: https://github.com/AveYo/D-OPTIMIZER/releases/tag/4.2 ?  

just check your launch options and autoexec.cfg for `anim_disable`  
or if you have that coreinit script present

**Comment by Fr33domJustice** [comment]
wow thanks man, it was that script, i typed UI into the console and i can toggle it now, soz for the inconvenience.
