### ISSUE TITLE
Missing Steampath error with batch script

### ISSUE THREAD

**Issue by DoulosTrieste** [No-Bling/DOTA#15]
![Clipboard01](https://user-images.githubusercontent.com/19621870/60287272-0dcee700-9944-11e9-881a-0060669d882f.jpg)

**Comment by AveYo** [comment]
should probably re-download the zip file from this git, I don't recognize any of that - it looks hijacked
Also, what OS is that?   
Keep in mind your antivirus might block the js parts of the script, so you should adress that as well

**Comment by AveYo** [comment]
hmm, quick google search and indeed it looks hijacked by something like trend micro officescan - either update that, get a newer windows 10 build, or better - get a competent av such as Avira that will not mess stuff up and is great for gaming ([here is a quick setup guide I made long ago](http://imgur.com/a/RJaea))

**Comment by DoulosTrieste** [comment]
I have the latest Win 10 build... I think I know what may be causing the problem. I have Emsisoft and Malwarebytes offline scanners, and using Windows Defender as main realtime scanner. Will report back.

**Comment by AveYo** [comment]
like I said, there is nothing wrong with the script, something on your system is hijacking it (you might have yet another shitty av scanner like I mentioned)

**Comment by DoulosTrieste** [comment]
But I don't. It's now just Windows Defender and Malwarebytes. It's not _only_ TrendMicro with their shitty coding skills, but a couple other programs that haven't been discovered with the same shitty coding skills. Python IDE? Visual Studio Code?

**Comment by DoulosTrieste** [comment]
Found the problem and uninstalled it.

https://github.com/rustyx/nobuzz
