### ISSUE TITLE
dotnet 3.5 requirement

### ISSUE THREAD

**Issue by 2c2c** [No-Bling/DOTA#16]
when i run the bat i get prompted by windows to install dotnet 3.5. put a lot of effort into installing it but am finally tapping out (some fluke win10 issue)

what in the script has this requirement? i did a quick read and didnt notice anything

**Comment by AveYo** [comment]
__vpkmod__ tool that does all the heavy lifting - it is made for maximum compatibility with naked Windows 7  
  
you can however unzip [tools\build vpkmod.zip](https://github.com/No-Bling/DOTA/blob/master/tools/build%20vpkmod.zip)    
then run `build csc vpkmod.bat` and it will create a `bin\vpkmod.exe` via default .net command line compiler  
finally replace the default vpkmod with the one you just compiled and it should work  

next version will probably come without pre-compiled tool and instead just create the tool on-the-fly from script
