### ISSUE TITLE
Alternative styles not adressed by Glance option

### ISSUE THREAD

**Issue by Managor** [No-Bling/DOTA#17]
Shoulders of Arsenal Magus and Cape of Arsenal magus when used with the Wex style are not blocked by no-bling.

I think the rest of the set and the rest of the styles are worthy of an investigation.

**Comment by AveYo** [comment]
There are no specific particles for that set.  
So it's not an issue with the default No-Bling mod, but with the you-know-what extra, limited support option.

**Comment by Managor** [comment]
Probably should have included a screenshot. Do you mean ++ build is the limited support option?
![image](https://user-images.githubusercontent.com/42655600/61244812-c2924200-a753-11e9-9692-659ddf498a79.png)

**Comment by AveYo** [comment]
yep, that's what I meant  
don't let that discourage you, I welcome any such reports and will try to fix it

**Comment by AveYo** [comment]
It's better to just update a single issue regarding alternative styles..
.. specially when none of them were working :)  

You should recheck those you found issues with as I have added automatic support in the script.

There are also specific manual filters for some you've reported like the golden naix and the smeevil ward (it uses a hard-coded 0.6 scale in items_game so when replaced with default it makes it huge, had to keep the base wearable style).

**Comment by Managor** [comment]
All of the alt styles that I can test with previous match summaries don't show the alt styles any more. I'll close this issue in a couple of days if I don't see any in the future.
