### ISSUE TITLE
Man, do you know how disable build in weather effects in custom terrains?

### ISSUE THREAD

**Issue by hasnogaems** [No-Bling/DOTA#2]
Like Immortal gardens, for example?

**Comment by hasnogaems** [comment]
Is there a way to replace this "petals on the wind" weather in Immortal gardens with default weather without builder? With notepad++ or something?

**Comment by KristenCruz** [comment]
I followed the instructions on the text file. Still couldn't remove those red particles on the immortal gardens. I even put the launch options both dota2 short cut and steam shortcut but no success.
What am i missing here?

**Comment by AveYo** [comment]
Maybe an image will help you more:
![nobling_dota_mod_manual_install](https://user-images.githubusercontent.com/12874843/43047515-cd8dde04-8de0-11e8-9eb1-ba67821fb620.png)

**Comment by KristenCruz** [comment]
That helped. I put the Launch option parameters on the shortcut itself. Now it works perfectly.
