### ISSUE TITLE
Unable to apply filters for Lina and Techies Arcanas via item ID.

### ISSUE THREAD

**Issue by CANADIANPIG** [No-Bling/DOTA#23]
I am attempting to whitelist the Lina Arcana per the personalized file. I was able to get the default shadow demon particles back up, but no dice on arcanas. I am using the script, a personalized file and all batch options except for menu. Based on what was provided I believe the script setting for the Lina arcana whitelist should be as simple as below.

[No-Bling-filters-personal.txt](https://github.com/No-Bling/DOTA/files/3420341/No-Bling-filters-personal.txt)

 ```
 //lina arcana
  "6879" "#"
```

Please let me know if I am simply making a mistake or if there is an issue.

**Comment by AveYo** [comment]
That's not the right number for lina arcana, it should be 4794 (actually 6879 is for techies).  
just run the script once with the verbose option, it will generate lots of files in log folder grouped by category and hero, and listing items with title + this id right in the name of the log file.  

But filtering needs a bit more work as it does not catch cases outside items_game.txt
