### ISSUE TITLE
Ability to remove new invoker skin

### ISSUE THREAD

**Issue by gurland** [No-Bling/DOTA#24]
Is there any ability to make default invoker? This [item from compendium](http://blog.dota2.com/2019/07/acolyte-of-the-lost-arts-invoker-hero-persona/) is kinda imbalanced because of you can't rapidly hit his hitboxes in fights due to reduced size of invo's model (his new model is almost like the circle beneath the hero in size).
![image](https://user-images.githubusercontent.com/30530987/61783585-bc195f80-ae10-11e9-9196-29c40290ab87.png)

**Comment by CANADIANPIG** [comment]
There is a note in the no-bling-filters list about this. You can restore the model of standard invoker, but the sounds will remain.

```
// restore kidvoker since orbs attachment is bugged volvooo 
  "models/heroes/invoker_kid/invoker_kid.vmdl"  "-"
  "models/heroes/invoker_kid/invoker_kid_cape.vmdl"  "-"
  "models/heroes/invoker_kid/invoker_kid_hair.vmdl"  "-"
  "models/heroes/invoker_kid/invoker_kid_sleeves.vmdl"  "-"
  // to replace kidvoker with default model anyway, comment above 4 lines and uncomment the following 3 
  //"models/heroes/invoker_kid/invoker_kid_cape.vmdl"  "models/heroes/invoker/invoker_shoulder.vmdl"
  //"models/heroes/invoker_kid/invoker_kid_hair.vmdl"  "models/heroes/invoker/invoker_head.vmdl"
  //"models/heroes/invoker_kid/invoker_kid_sleeves.vmdl"  "models/heroes/invoker/invoker_dress.vmdl"
```

**Comment by gurland** [comment]
Thanks a lot, it helped!
