### ISSUE TITLE
Hero Icons Disppearing

### ISSUE THREAD

**Issue by CANADIANPIG** [No-Bling/DOTA#25]
...There also appears to be a bug with the icons (when you have a skill point available, the icon of the ability which you can upgrade will disappear until you level it up).

_Originally posted by @eVen-gits in https://github.com/No-Bling/DOTA/issues/14#issuecomment-504768036_

I am not sure if this issue has already been solved/addressed, but this issue still persists.

**Comment by eVen-gits** [comment]
Hello,

I've made a bit of a research, I don't think it's No-Bling/DOTA related. Some other people have reported the issue, from what I can gather, it's Vulkan related.

So if I am correct, this bug is experienced by literally everyone that's on Vulkan API.

**Comment by CANADIANPIG** [comment]
Dang it. Oh well, I switched to Vulkan as I had crashing issues on DX for some unknown reason. I will try OpenGL.

Thanks!

**Comment by eVen-gits** [comment]
@CANADIANPIG just a word of caution - OpenGL has significantly worse performance and will probably not be developed further much. It's sort of obsolete.
