### ISSUE TITLE
Glance is not replacing the Smeevil's Penance ward

### ISSUE THREAD

**Issue by Managor** [No-Bling/DOTA#26]
Build: Custom
Cosmetic visible:
Smeevil's penance
![Screenshot_2019-08-13_21-58-22](https://user-images.githubusercontent.com/42655600/62969247-87983280-be15-11e9-97b9-1c03b8e034ce.png)

There are a couple of wards in this list that are shown with a different size. Those are
Hellgazer
Black Pool Watcher
Staff of Faith
Spring Ward
as seen right next to Smeevil's Penance

**Comment by AveYo** [comment]
there is another issue referring smeevil - unfortunately valve uses different scale so if the ward is replaced with the default one it looks way oversized  
as  a compromise all alternative colorfull styles have been disabled

**Comment by AveYo** [comment]
those should have close enough scale, unlike the smeevil that was 1.6x
