### ISSUE TITLE
How would i remove this if i had set it up with the auto installer?

### ISSUE THREAD

**Issue by gkpunk** [No-Bling/DOTA#27]
I set up Dota Bling with the batch file however i accidentally removed taunts aswell. I want to have the taunts so i thought i could remove it and reinstall it again but how do i do that? I can not find anything related to it since i did not set it up manually. I tried verifying the game cache but it did not work.

**Comment by AveYo** [comment]
just run the script again with other options it will override existing mod..  
if you must, you can delete `pak01_dir.vpk` from `game\dota_tempcontent` folder

**Comment by gkpunk** [comment]
thanks!
