### ISSUE TITLE
Is there a way to filter models in "Glance" AKA Gabening mode?

### ISSUE THREAD

**Issue by ryamshin** [No-Bling/DOTA#28]
As a test I tried adding  
"10091" "#"
in the "Glance" {} section. 10091 should be Baby Roshan, but when I enter the game, Baby Roshan is still the Dire courier.

**Comment by AveYo** [comment]
It's incomplete and bugged.  
Custom filtering needs refactoring badly - for starters the personal file should only need the specific filters, not be a complete duplicate of the "official" one. TODO

**Comment by AveYo** [comment]
Well, it's happening.  
Note that GlanceValue no longer affects couriers.
