### ISSUE TITLE
Golden Profane Union is visible again

### ISSUE THREAD

**Issue by Managor** [No-Bling/DOTA#29]
Build: Custom
![Screenshot_2019-09-09_16-05-35](https://user-images.githubusercontent.com/42655600/64533294-d5705f80-d31b-11e9-8a85-e74537614aff.png)

![Screenshot_2019-09-09_16-07-17](https://user-images.githubusercontent.com/42655600/64533343-ea4cf300-d31b-11e9-96d1-fd4b1c316bc0.png)

**Comment by AveYo** [comment]
That's clearly an UI bug on your end - it happens often when the coordinator goes temporarily offline and cosmetics get mixed up (plenty of reddit funny posts with this stuff).

**Comment by Managor** [comment]
Ah, thanks. Haven't seen that before.
