### ISSUE TITLE
Choice of language

### ISSUE THREAD

**Issue by aacprime** [No-Bling/DOTA#3]
I'm using Russian interface of Steam and English interface of Dota 2 via "-language english" launch option.
Mod builder .bat file automatically installs everything in dota_russian folder, which is no use for me. Because of that I've been installing your builds manually.
It's more of a request than an issue - I ask you to let us choose installation folder when installing mod using .bat file.

**Comment by AveYo** [comment]
It's already there in the script line 39:
`rem set "MOD_LANGUAGE=english"         || rem = current Steam language is auto-detected, override here`  

Just uncomment it by removing preceding `rem ` like this:
`set "MOD_LANGUAGE=english"         || rem = current Steam language is auto-detected, override here`

**Comment by AveYo** [comment]
v7.16 r1:  Added support for persistent language override.   
To define it, open a command prompt and enter:   
`setx NOBLING_LANGUAGE english`  
_Adjust `english` to your preference_  

Can also define it via `rundll32 sysdm.cpl,EditEnvironmentVariables`
