### ISSUE TITLE
weather particle effects

### ISSUE THREAD

**Issue by pochopopos123** [No-Bling/DOTA#30]
Bro i really like your work. But i have a suggestion, How about disable the weather particle effects? Like Pestillence weather but no rain and bugs crawling on ground. I just like the color of the weather. can u help me? plss and thanks in advance

**Comment by pochopopos123** [comment]
And how about I only have items and the others not? plss notice me ;-)

**Comment by pochopopos123** [comment]
the spring weather was fixed, No petals drops and it boost my fps. plss help me to fix the other weather effects.( sorry for bad english not my language)..

**Comment by AveYo** [comment]
Only bundled weather that comes with terrains have been tweaked, all others that you can equip separately are not touched. The idea was that if it's heavy then you can simply unequip it, but now if I think about it maybe I would keep my moonlight weather enabled if there were no dragon flies..  
So thank you for the suggestion, I will try to add support for all weather effects in the next big update!

**Comment by pochopopos123** [comment]
I gain more fps on tweaked spring weather than the normal weather so it really helps if you tweak the other weather effects.thanks for the notice and I use your cfg since 2017. keep the good job!!

**Comment by Slaviusz** [comment]
Hi there. Thank you for your great work.
I'd also like to remove particles from some custom weather - Ash. I generally like the mood (color, lighting) of the weather but dislike the overused particles. IF there would be a way to remove them completely - I'd be very thankful.

**Comment by AveYo** [comment]
It's already moved high on the todo list for the next update.
