### ISSUE TITLE
I have an issue with installation.

### ISSUE THREAD

**Issue by shelmor123** [No-Bling/DOTA#31]
https://i.imgur.com/1t1zgCQ.png cannot open something

**Comment by Anutrix** [comment]
Same issue

**Comment by AveYo** [comment]
Back in beta, hopefully a new release before June 1st! Bare with me :)

**Comment by Anutrix** [comment]
Do add the option or even details about what to do when Dota/SteamLibrary is not in the default location.
I got this error after modifying bat file.
Before modifying the path in around lines 400, it wasn't finding anything and just saying 
```00:00:01.29
 ERROR ! Missing "c:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game"```

**Comment by AveYo** [comment]
I have changed detection in the new script  
You can easily override it if needed by defining the STEAMPATH variable in the script

**Comment by Anutrix** [comment]
Thx
