### ISSUE TITLE
Is there a way I can only see my hero hats but the others dont?

### ISSUE THREAD

**Issue by pochopopos123** [No-Bling/DOTA#32]
Hello its me again, As I said in the title is there a way or can you add it on your next update features? It will be so good if it does. your no bling mod was so popular in my neighborhood because i introduce it to them. Plss make it possible if u can 😄

**Comment by AveYo** [comment]
No. This is a passive mod that applies globally.  
It can't differentiate your hero from others, nor it can know in advance what are your equipped cosmetics.  
I suppose a dynamic  hack could be done by hijacking panorama js during multiplayer games but I won't get into such dangerous ban-able stuff.

**Comment by pochopopos123** [comment]
Ok but how about to allow some items in glance option? I know it was mention on "How can I manually allow certain effects" but i dont know how to do it. I'm not an I.T. expert. Can u make a video about how to do it? I sub on your youtube channel sorry I have so many request recently :3
