### ISSUE TITLE
nothing change after installing the script :(

### ISSUE THREAD

**Issue by dzanfranko** [No-Bling/DOTA#34]
Hi all, 
I tried installing the script on 2 different computers but the result is the same, nothing changes except all my heroes have default items... Can someone help me or explain to me did I do something wrong? I want to see arcana and hero taunts and other cool stuff :)

**Comment by AveYo** [comment]
Wrong title as something did change, but it was not what you've expected ;)
It's working as intended! 
This project simply reverts cosmetics to defaults - not unlocking stuff for you..

**Comment by dzanfranko** [comment]
Oh, my bad then :) 
I thought that I can use arcana, taunts, etc. but nobody but me can see that... 
Sorry for the misunderstanding.
