### ISSUE TITLE
knock knock xD

### ISSUE THREAD

**Issue by Fr33domJustice** [No-Bling/DOTA#35]
ya purple guy ate my fps again, pls send help

**Comment by Wolf49406** [comment]
Main menu also

**Comment by meatgrind89** [comment]
SOS Please send help

**Comment by AveYo** [comment]
this December 💃

**Comment by Fr33domJustice** [comment]
AveYo working for Valve with the Valve time Pog

**Comment by AveYo** [comment]
Indeed :)  
Did not expect Valve to release Ogre Arcana before Christmas, but they did!   
... and such a low-effort must be answered A.S.A.P.  

Dear IceFrog, please grant me +2 strength so that I may finish this mod rework..
