### ISSUE TITLE
Void Spirit and Snapfire minimap icons missing / Update for 7.23

### ISSUE THREAD

**Issue by hauzer** [No-Bling/DOTA#37]
Love your work, thanks!

**Comment by AveYo** [comment]
finally back at home with my trusted desktop potato and premium internet, already actively working on reforging the mod! will try to release a hotfix for the old builds sooner

**Comment by sadlyfell** [comment]
@hauzer 
Extract this into NO-Bling folder, you should have one already from previous build. Replace all if its asking. These files fix minimap and tweak main menu animated background. If you prefer have animated background just go into pak01_dir folder that you extract already and delete panorama folder.
[pak01_dir.zip](https://github.com/No-Bling/DOTA/files/3918927/pak01_dir.zip)

**Comment by hauzer** [comment]
@sadlyfell Works great, thanks a bunch!

**Comment by Fr33domJustice** [comment]
@sadlyfell dude i thot i was trippin when both purple and grandma at my team and they all just blank icons, thanks a lot !

@AveYo doing the god work here, keep it up man !

**Comment by zero57** [comment]
Does this still work @sadlyfell ? I'm replacing the files in the NO-Bling folder, and re-running the build script again, but I'm still seeing void spirit/snapfire missing the minimap icons. I have all the choices selected, and I tried unchecking `@update` and `@refresh` when building, but it's still not working.

@AveYo Is there going to be an official update to fix this issue soon?

Thanks.

**Comment by Mackzwellz** [comment]
Either use "materials\vgui\hud\minimap_hero_sheet_psd_3529892a.vtex_c" from game archives (you can view and extract files using GCFScape), or remove the file (actually there are two copies) from nobling directory before building.
If you remove the file before building, you will see modified icons (like Zeus with arcana) on minimap if someone has item that modifies the icon equipped. A minor caveat for improved compatibility, if you ask me.

**Comment by KerzaGG** [comment]
@sadlyfell is there an updated method for your fix?

**Comment by KerzaGG** [comment]
@Mackzwellz I don't know how to use GCFScape and apparently the website to download it is dead so I am using your way. It works so far just hope it does not confuse me the hero with the minimap icon haha. thank you!

**Comment by coldshouldermedia** [comment]
Please release an update fixing this issue.  I've just left their icons invisible for now.

**Comment by Lethalmathematix** [comment]
Hey, @AveYo 
Do you need any help with the rework?
I've got plenty of time to pitch in these days. :)

**Comment by AveYo** [comment]
I have drifted from DOTA completely, sorry. 
Will check it out these days.

**Comment by KerzaGG** [comment]
Based AveYo thank you for coming back to us, our hero in need
