### ISSUE TITLE
The problem with the English voice acting.

### ISSUE THREAD

**Issue by RexonD** [No-Bling/DOTA#4]
Hi, my problem is connected with the change of the Russian language into English. I use No-bling and I want to use only English voice acting instead of Russian, and I want to leave the interface language the same, but when i change language to english, No-bling stops working. I tried to solve the problem on my own, tried various methods to also clean your description, but nothing came of it. How do I solve this problem? I use Steam client in Russian

**Comment by AveYo** [comment]
What is the language you use for the interface (text) in DOTA, Russian or English?

**Comment by RexonD** [comment]
I use Russian

**Comment by AveYo** [comment]
To get rid of the Russian voice translations you could simply delete everything under:  
`\steamapps\common\dota 2 beta\game\dota_russian`   
Then install No-Bling mod as usual with the auto-detected `-language russian`  

No-Bling supports overriding the auto-detected language if needed - in a Command Prompt, enter:   
`setx NOBLING_LANGUAGE english`  

I guess I could add support in the script for overriding russian language without deleting the content, the same as I do for english with the `%` sign at the end of the name.

There is also [dota_primary_mm_language_override_v6.bat](https://gist.github.com/AveYo/3930ef9ab455b858f08cce4ea790509a) to set custom choices for ui / matchmaking.

**Comment by RexonD** [comment]
I deleted the "dota_russian" voice folder and really became English, but No-Bling stopped working. He also did not define `-language russian`, he also entered the command `setx NOBLING_LANGUAGE english` nothing has changed. During the launch, I didn’t go to Steam, the Russian was in the DotA’s parameters.  I attach a screenshot of the log :
![log](https://user-images.githubusercontent.com/38333464/48916186-5e540280-ee92-11e8-818d-54056cfa30f9.png)

**Comment by AveYo** [comment]
Well you were supposed to adjust the command for your specific need. You need russian instead:  
`setx NOBLING_LANGUAGE russian`

**Comment by RexonD** [comment]
It worked! Thank you for help!
Regarding the support for redefinition for the Russian language without deleting the content is a great idea :)

**Comment by AveYo** [comment]
Fixed in next update, mod is language independent again!
