### ISSUE TITLE
No bat files

### ISSUE THREAD

**Issue by belphegorspn** [No-Bling/DOTA#44]
Hi, im new to this stuff. I've read this on reddit. I wanted to try it out and after watching a few tutorial videos I noticed they had bat files. Whenever I download and extract the files there are no bat files present so I cant mod my game :( can someone help me please?

**Comment by AveYo** [comment]
A new version is in the works, bare with me

**Comment by belphegorspn** [comment]
okay, my bad! thank you so much for doing this for us. :)
