### ISSUE TITLE
Needed linux script

### ISSUE THREAD

**Issue by shpinog** [No-Bling/DOTA#5]
It would be great to have a script for linux

**Comment by AveYo** [comment]
Guess so.. care to help with that? :)  
On the long run I wanted to move to powershell, and that would mean it could run on both Linux and MacOS. 
But there is not much interest to the Windows version, you could imagine the Linux interest until your post.. not so much.  
I won't make any promises, but it could happen.
Mean time you can use the pre-made builds just fine.

**Comment by shpinog** [comment]
Im use pre-made builds, copy file to dir, but nothing has changed, 0 effect, and in English and Russian

**Comment by AveYo** [comment]
[maybe this would help](https://github.com/No-Bling/DOTA/issues/4)

**Comment by ConnahGriffin** [comment]
I'm just here to state that I'd also love the linux version

**Comment by AveYo** [comment]
Sad

**Comment by romainrbr** [comment]
> Im use pre-made builds, copy file to dir, but nothing has changed, 0 effect, and in English and Russian.I use linux

Same issue here, I have copied the binary (tried all 3 versions) in `~/.steam/steam/steamapps/common/dota 2 beta/game/dota_tempcontent`, and added `-tempcontent` to the launch options, but I can still see all hats in game.

Running dota in english on ubuntu 18.10.
Nothing in the console log either.

**Comment by TazmanOne** [comment]
macOS support please

**Comment by AveYo** [comment]
> > Im use pre-made builds, copy file to dir, but nothing has changed, 0 effect, and in English and Russian.I use linux
> 
> Same issue here, I have copied the binary (tried all 3 versions) in `~/.steam/steam/steamapps/common/dota 2 beta/game/dota_tempcontent`, and added `-tempcontent` to the launch options, but I can still see all hats in game.
> 
> Running dota in english on ubuntu 18.10.
> Nothing in the console log either.

Works just fine on my end, ubuntu 19.04, mod installed in: 
`/home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/dota_tempcontent/pak01_dir.vpk`   

DOTA log:  
```
[Filesystem] EXECUTABLE_PATH      "/home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/" 
[Filesystem] GAME                 "/home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/dota_tempcontent/pak01.vpk" (vpk) /home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/dota_tempcontent/pak01.vpk
[Filesystem] GAME                 "/home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /home/x/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk
[CommandLine] command line arguments:
[CommandLine] +engine_experimental_drop_frame_ticks 1 -tempcontent -console -consolelog -conclearlog
```

**Comment by eVen-gits** [comment]
+1 the mod works on Pop_OS as well, but I don't know if the linux script is working - I used built vpks.

**Comment by mohammadanton** [comment]
this is not working on my linux, is this because I use custom steamapps directory?

Im not usinng the defaultl steamapps directory (.locall//share/Steam...)

**Comment by eVen-gits** [comment]
Depends on what is not working for you. If you are thinking about the script, there are various reasons - mainly because it's written in batch (.bat).

If you mean the prebuilt packages, then they are working, you just have to move them to the correct path and enable them.

If you are trying to run the batch script in Wine environment, it will work somewhat - you need to tweak environment variables which contain paths and replace some commands, but even then I am not sure if it'll work - I didn't manage to get the builder to work under linux.

**Comment by mohammadanton** [comment]
can you tell me what envi variable that i need to correct?

**Comment by eVen-gits** [comment]
Not by heart, sorry.

You can run it in terminal like so: `wine cmd /c file.bat`

It will print out the errors. But as I said, even if you fix the paths manually, it won't work, at least not in my experience. Use the prebuilt .vpk files which you can find [here](https://github.com/No-Bling/DOTA/tree/master/BUILDS)

**Comment by eVen-gits** [comment]
Where did you place the .vpks and which ones did you use? And what is/isn't working?

**Comment by mohammadanton** [comment]
> Same issue here, I have copied the binary (tried all 3 versions) in `~/.steam/steam/steamapps/common/dota 2 beta/game/dota_tempcontent`, and added `-tempcontent` to the launch options, but I can still see all hats in game.
> 
> Running dota in english on ubuntu 18.10.
> Nothing in the console log either.

like this one

**Comment by eVen-gits** [comment]
Well the directory is correct if you game is actually located there. If you have a custom steam library path, you have to copy it into that dirrectory.

So in my example, it would be `/home/<uname>/SteamLibrary/steamapps/common/dota 2 beta/game/dota_tempcontent`.

In your case, it would be `<your_steam_library_path>/steamapps/common/dota 2 beta/game/dota_tempcontent`.

**Comment by mohammadanton** [comment]
sorry for my lack of detail, but I already add folder dota_tempcontent(with vpk) in my steam library path.

maybe because my steam library path not default so I try to symlink the folder but not working

ln -s /mnt/655e643e-4b45-43ae-a2b5-fa4ce39ce4c1/ssteamlibrary/steamapps /home/me/.local/share/Steam/steamapps

**Comment by mohammadanton** [comment]
it's working now, the VIP01 in BUILDS/++ working well, buut BUILDS/full (not working).

work great on my arch :)

**Comment by AveYo** [comment]
Thank you @eVen-gits for assisting @mohammadanton 💯   

__New build is up, with improved filters!__  
Also updated readme with info on how to quickly get to the correct `dota 2 beta` folder:  

> If you have trouble locating the path, right-click Dota 2 in Steam Library window - Properties - Local files - Browse local files  
> That should lead you to `\steamapps\common\dota 2 beta`  
> Enter `game` subfolder, then create folder `dota_tempcontent` and copy `pak01_dir.vpk` in there  
>

**Comment by AveYo** [comment]
Linux script is up, feedback welcomed!

**Comment by eVen-gits** [comment]
I'll try to check it up in the future. I am no longer playing the game so I don't have it installed, but I'll try to run the script and contribute if possible.

Thank you for your care and work!
