### ISSUE TITLE
Newsest version no longer working

### ISSUE THREAD

**Issue by destructive-dragon** [No-Bling/DOTA#6]
When I try to update, this happens:

![image](https://user-images.githubusercontent.com/4991312/50528235-5587c980-0aed-11e9-9482-76e9402f8be3.png)

**Comment by AveYo** [comment]
Yeah I might have barked some stuff with the significant filtering move.  
Working on fixing it.

**Comment by AveYo** [comment]
@destructive-dragon Bump!  
Try out the new version!
