### ISSUE TITLE
Invalid App Configuration

### ISSUE THREAD

**Issue by RazeAE** [No-Bling/DOTA#69]
This keeps popping up after using no bling mod. anyone got a fix for this?

**Comment by konstantinpachemski** [comment]
Any screenshots or ways of reproducing this? 

Are you using Vulkan by any chance? 
Have you tried verifying game data and rerunning No-Bling? 
Have you checked if the steam directory path is set correctly in No-Bling-builder.bat?

**Comment by RazeAE** [comment]
> h is se

I'm currently using dx11
Yes i have tried that many many times now
I didn't know about this method can you teach me? 
Also the this version of no bling dota mod isn't working as well as the other previous versions.
