### ISSUE TITLE
Question: This Mod for MacOS

### ISSUE THREAD

**Issue by vincetran96** [No-Bling/DOTA#71]
Does this mod improve the FPS when running Dota 2 on MacOS? Thanks!

**Comment by zxjloh** [comment]
> Does this mod improve the FPS when running Dota 2 on MacOS? Thanks!

It seems to improve on my M1 mac. I used a windows machine to first generate the file then place it in the folder: /.../steamapps/common/dota 2 beta/game/dota_tempcontent, and add "-tempcontent" in launch options!
