### ISSUE TITLE
Further Development of this Project

### ISSUE THREAD

**Issue by githubplanetarparrot** [No-Bling/DOTA#73]
Hello AveYo,

What is needed to expedite development on this project. What are we able to help with to get this program updated? 

Thanks.

**Comment by XkTheMaster** [comment]
Yeah we really need an update. These new voice lines from teams are annoying asf, also pudge/am persona, qop/wk/wr arcana needs to be fixed. Will there be an update for it ? Or did u gave up ?

Thanks.

**Comment by NamNguyen-hub** [comment]
+1 , willing to help. The project needs an update

**Comment by carmelopaz0708** [comment]
+1 for help as well. Please don't let this project die. Tell us what needs updating and we'll be on it.

**Comment by xetrael** [comment]
+1 the project needs an update..

**Comment by robbyz512** [comment]
@AveYo not trying to insult you by posting my project here, but since no-bling isnt monetized or in active development, I hope you wont mind!

@CANADIANPIG @XkTheMaster @NateNg @carmelopaz0708 @etherealzxcqwe 

To ease some of you're worrying, I've been working on a particle reduction modkit for dota. Here's some screenshots

https://imgur.com/a/MguaRbU

It will do everything no-bling does and several more things, most notably I'm modding every spell and item and effect in the game to show only basic animations without any useless flashy effects like embers/flames/electricity/dust...etc

video previews
[Void Spirit Minified and Default Comparison](https://streamable.com/41b1hr)
[Dawn & Phoenix Minified and Default Comparison](https://streamable.com/8fd4go)
[Minify team fight benchmark](https://streamable.com/j2b1fn)
[Default Dota team fight benchmark](https://streamable.com/l1nkz7)

gives a big jump in fps and makes team fights way less distracting, add me on discord if you are interested in following it or helping to develop. 👍 
Discord: robby#1039

**Comment by robbyz512** [comment]
> 
> 
> Yeah we really need an update. These new voice lines from teams are annoying asf, also pudge/am persona, qop/wk/wr arcana needs to be fixed. Will there be an update for it ? Or did u gave up ?
> 
> Thanks.

I have removed all the new DPC voice lines, they add more every week but these are the latest patched ones as of 05/31/21
https://www.mediafire.com/file/imgds9fkukaibjb/sounds.7z/file

you'll have to manually create a vpk file with vpkcreator. If you don't know how just message me on discord i'll help you out.

robby#1039

**Comment by jereloh** [comment]
> @AveYo not trying to insult you by posting my project here, but since no-bling isnt monetized or in active development, I hope you wont mind!
> 
> @CANADIANPIG @XkTheMaster @NateNg @carmelopaz0708 @etherealzxcqwe
> 
> To ease some of you're worrying, I've been working on a particle reduction modkit for dota. Here's some screenshots
> 
> https://imgur.com/a/MguaRbU
> 
> It will do everything no-bling does and several more things, most notably I'm modding every spell and item and effect in the game to show only basic animations without any useless flashy effects like embers/flames/electricity/dust...etc
> 
> video previews
> [Void Spirit Minified and Default Comparison](https://streamable.com/41b1hr)
> [Dawn & Phoenix Minified and Default Comparison](https://streamable.com/8fd4go)
> [Minify team fight benchmark](https://streamable.com/j2b1fn)
> [Default Dota team fight benchmark](https://streamable.com/l1nkz7)
> 
> gives a big jump in fps and makes team fights way less distracting, add me on discord if you are interested in following it or helping to develop. 👍
> Discord: robby#1039

Interested in this! where can we try it?

**Comment by robbyz512** [comment]
> Interested in this! where can we try it?

it's still developing, you can add me on discord and ill send you a pm when it's ready to be tested

**Comment by acurrysauce** [comment]
Does this work at all for anyone anymore? Can't get taunts or cosmetics to be disabled.

**Comment by AveYo** [comment]
_The Prodigal Son Returns.._   ;)

**Comment by staaandup** [comment]
Hi, i want to know if its possible to make ALL heroes be default/have 0 Cosmetics on them except for 5 or 6 heroes that i play regularly.. if i can have cosmetics on CK, Legion, Enigma, Treant, Pudge, and all the rest of the heroes be default it would be marvelous... maybe if someone can give me an example or a line that i just add to the 'No-Bling-filters.txt' file and i will do the rest of the heroes my self.. again, if thats even possible? ;p

im using No-Bling with these settings (default)
https://i.imgur.com/bKplVsV.png

and also this is my current 'No-Bling-filters.txt' file

"user-filters"
{
  //======================================================================//
  //       | spells and immortals/items to keep, to use them!! ;P |       //
  //======================================================================//
  keep_ability    "8326"
  keep_item       "4997,5337,5810,7059,7060,7061,7062,7692,7878,7930,8057,8060,9058,9196,9214,9236,9682,9722,9772,12290,12434,12918,14991"
  //======================================================================//
  //                  | remove all ambient effects |                      //
  //======================================================================//
  391 { visuals{} } 
  483 { visuals{} } 
  498 { visuals{} } 
  501 { visuals{} } 
  502 { visuals{} } 
  503 { visuals{} } 
  504 { visuals{} } 
  505 { visuals{} } 
  506 { visuals{} } 
  507 { visuals{} } 
  508 { visuals{} } 
  509 { visuals{} } 
  510 { visuals{} } 
  511 { visuals{} } 
  512 { visuals{} } 
  513 { visuals{} } 
  514 { visuals{} } 
  515 { visuals{} } 
  516 { visuals{} } 
  517 { visuals{} } 
  518 { visuals{} } 
  519 { visuals{} } 
  520 { visuals{} } 
  521 { visuals{} } 
  522 { visuals{} } 
  523 { visuals{} } 
  524 { visuals{} } 
  525 { visuals{} } 
  526 { visuals{} } 
  527 { visuals{} } 
  528 { visuals{} } 
  529 { visuals{} } 
  530 { visuals{} } 
  531 { visuals{} } 
  532 { visuals{} } 
  533 { visuals{} } 
  534 { visuals{} } 
  535 { visuals{} } 
  //536 { visuals{} } //big nope for io/wisp, it becomes invisible..
  537 { visuals{} } 
  538 { visuals{} } 
  539 { visuals{} } 
  540 { visuals{} } 
  541 { visuals{} } 
  542 { visuals{} } 
  543 { visuals{} } 
  544 { visuals{} } 
  545 { visuals{} } 
  550 { visuals{} } 
  553 { visuals{} } 
  600 { visuals{} } 
  601 { visuals{} } 
  602 { visuals{} } 
  605 { visuals{} } 
  617 { visuals{} } 
  630 { visuals{} } 
  631 { visuals{} } 
  653 { visuals{} } 
  669 { visuals{} } 
  684 { visuals{} } 
  690 { visuals{} } 
  746 { visuals{} } 
  7555 { visuals{} } 
  7556 { visuals{} } 
  8362 { visuals{} } 
  8363 { visuals{} } 
  8365 { visuals{} } 
  8371 { visuals{} } 
  8625 { visuals{} } 
  8627 { visuals{} } 
  8630 { visuals{} } 
  8636 { visuals{} } 
  8638 { visuals{} } 
  8640 { visuals{} } 
  8643 { visuals{} } 
  8644 { visuals{} } 
  8645 { visuals{} } 
  8646 { visuals{} } 
  8652 { visuals{} } 
  14293 { visuals{} } 
  14294 { visuals{} }
}

**Comment by verydarkmagic** [comment]
@robbyz512 any public repo available ?

**Comment by locetob930** [comment]
> it's still developing, you can add me on discord and ill send you a pm when it's ready to be tested

@robbyz512 whats your discord tag? and any news?

**Comment by metapodcod** [comment]
@robbyz512 your discord address is wrong, if you share this you will make millions of low pc gamers happy

**Comment by lordamir20132** [comment]
@metapodcod 
did u get any way to contact him i want the mods too

**Comment by metapodcod** [comment]
> @metapodcod did u get any way to contact him i want the mods too

no, i guess he doesn't want to share :(
