### ISSUE TITLE
future of this mod

### ISSUE THREAD

**Issue by ryouik1** [No-Bling/DOTA#76]
https://www.reddit.com/r/DotA2/comments/s46mj8/dota_2_update_for_11422_11522_utc/?utm_source=share&utm_medium=web2x&context=3

Is it possible to do smth to bypass this block?

**Comment by Wolf49406** [comment]
no

**Comment by ryouik1** [comment]
no

**Comment by XkTheMaster** [comment]
@Wolf49406 any update so far ?

**Comment by Wolf49406** [comment]
> @Wolf49406 any update so far ?

Not really. Valve removed -tempcontent, so the only way to do vkp is by editing gameinfo.gi.
There is hardcoded CRC32-hash of gameinfo and pretty stupid check of it and file size.
Wich i can easily bypass by patching just one byte and there will be no "VAC" error. 
But there is also same check of (AFAIK) literally EVERY file in vpk.
I can bypass it by hooking GC, but it's not a legit way. So... yeah. Work in progress.

**Comment by XkTheMaster** [comment]
Theres 1 more way with -language , same thing as tempcontent but u have to create a folder in game like dota_xxx then adding -language xxx @Wolf49406

**Comment by Wolf49406** [comment]
@XkTheMaster yeah for now at leas. But you still have to patch some dll's to back vpk.
I'm pretty sure it's just a generic if\else check like with gameinfo.gi so it's not a big deal to bypass.
The problem is to find right place in code.

**Comment by AveYo** [comment]
I have stopped improving this mod, after an avalanche of *"you're killing dota"* feedback.
Maybe I should have disregarded the loud opinions of $$ invested moddota cunts, content creators, pro-players, slacks and friends, making waves behind reddit aliases. 
But they are well connected to the scene, and repeatedly tried to push Valve into disabling mods.
So I've "disappeared".

Did they finally get their wish?
While it seems so, it might just be Valve's janitor fault so I won't raise any pitchfork. 

- This mod started out with `-lv` launch option (for dota_lv folder).  
- Was removed I think with Source 2.

- Switched to `-language` but that one was less convenient _(to override english and keep ui language files & etc had to invent stuff like -language `english%` with `dota_english%` folder)_.

- So I've introduced the better `-tempcontent` and has been fine for years. Other mods adopted it.
Now that's gone.
Guess we go back to the cumbersome `-language` as it appears to still work fine.
Winter is here, so the soon™ No-Bling update, is happening.

**Comment by Wolf49406** [comment]
Guys i did it, i patched god damn dll. Screen from game with NoBling enabled.
![image](https://user-images.githubusercontent.com/26302888/149777190-515cff21-49dc-44d6-9720-5e745b2a95d6.png)

**Comment by XkTheMaster** [comment]
@AveYo there's no way you actually came back XD and giving an update for this project, i think im dreaming. But for now is there a safe fix for mod ?

**Comment by AveYo** [comment]
Hex editing `client.dll` like Wolf49406 does has always been a huge no-no for VAC

`-language` switch has always been VAC safe

If Valve wants to really kill modding, they can block resource loading outside `dota`
I'm not sure is something they want, tho.
So I'm gonna update the mod and see if they take further action.

**Comment by robbyz512** [comment]
@AveYo 
> I have stopped improving this mod, after an avalanche of _"you're killing dota"_ feedback. Maybe I should have disregarded the loud opinions of $$ invested moddota cunts, content creators, pro-players, slacks and friends, making waves behind reddit aliases.

create your own community and surround yourself with like minded people, no point of trying to win the respect of computer illiterate scrubs on reddit. And as for the moddota crowd, I just take advantage of them haha when they get suspicious of me asking questions about editing props and terrain and stuff in the dota map I just say it's some how related to a custom map project. 

If you make a forum I'll share all my mods there.

**Comment by XkTheMaster** [comment]
@ryouik1 @MadSochi Someone found a fix and I will try to explain how to do it until Aveyo will update No-Bling.
We will need this tool https://github.com/rr-/CRC-manipulator extract it, inside it there should be crcmanip-cli.exe which we would use it later in CMD.

Now go to common\dota 2 beta\game\dota directory
1. Inside it there is gameinfo.gi we will edit it (remember the original gameinfo.gi has 7.708 bytes) 
2. Rename `gameinfo.gi` to `gameinfoModified.gi` then go inside it with notepad++
3. There you will add new lines above  `Game -- dota` and `Mod -- dota` line 43 and 47 (in notepad)

- Game dota_tempcontent `(4 tab's between Game and dota_tempcontent)`

- Mod dota_tempcontent `(4 tab's between Mod and dota_tempcontent)` 

4. At line 4 `"gameinfo.gi is the non-branch-varying content and can be integrated between branches."` 
 Remove text until you get `"gameinfo.gi is the non-"`
5. Save the file, now the file should have 7.704 bytes.
6. Go into CMD, change directory to crcmanip-0.5.2-bin
7. Now paste this command 
`crcmanip-cli.exe patch "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\gameinfoModified.gi" "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi" 4a52fc4f -p 18 -a CRC32`
10. After that it should create a new gameinfo.gi with 7.708 bytes and you should still have the old gameinfoModified.gi with 7.704 bytes 
11. If ur `new gameinfo.gi` did not get +4 bytes after the patch, u did something wrong.
11. You can now enjoy and play with No-Bling Mod.

**Comment by Wolf49406** [comment]
Patching client.dll was never a problem because VAC never checked it. Many people have been patching camera distance this way for years.
And I even have a repo with a patcher, which I myself have been using for years.
You can even patch it on run-time, not just static patch. Anyway, here's what i found.
Open client.dll in ida, go to strings, search for "PlayDisabled_LocalFiles". 

Here it is, simple CRC and file size check.
![image](https://user-images.githubusercontent.com/26302888/149850504-ae3d027d-a9f6-4171-b1d6-a0cecfdb7f67.png)

The green one -- is our place to patch.
![image](https://user-images.githubusercontent.com/26302888/149850561-8cf53ca8-942f-4db3-8739-c6b577656f73.png)

So all you have to do is change jz short loc_18170E520 to jmp (74 >> EB)
Now you can do generic gameinfo stuff.
Pattern, if someone needs it "44 38 67 39 74 39". Our byte is (Pattern + 4);

Ghetto way: Open HxD Hex Editor > Ctrl+F > Hex > My Sig > Change 74 to EB
![image](https://user-images.githubusercontent.com/26302888/149851380-13eaf3bb-2201-41ce-8f05-67aeccc6f716.png)

**Comment by lordamir20132** [comment]
i had a friend on discord he gave me a mod to change map textures to something easier on hardware and a mod for disabling some more effects on hero abilitys like phonix and void became so nice and simple on the eye can someone please fix it for me
[mod.zip](https://github.com/No-Bling/DOTA/files/7889132/mod.zip)

**Comment by Wolf49406** [comment]
@lordamir20132 are you retarded? We gave you 3 ways to fix your shit. Do somethings yourself.

**Comment by lordamir20132** [comment]
uhm calm down sir im just a normal player and this mod should be different from no bling i just wanted to share it with u guys sry

**Comment by MadSochi** [comment]
Please don't make from this Issues forum the scum forum.

**Comment by lordamir20132** [comment]
@robbyz512 hey man u have been away from ur discord for a long time are you doing ok? how is the mods going?

**Comment by MadSochi** [comment]
@XkTheMaster

Thank you for the perfect step by step instruction. But...
A little misunderstanding.
How must looks like the lines from line 40 to line 60.
Like this?
https://gyazo.com/a0dc69ee13026ab867c17c8147ffd156

or like that?
https://gyazo.com/358ef2bd09faba638c142b9bc2da57c4

Anyway i can not get 7.704 bytes of gameinfoModified.gi

With line 4 is everything fine i think.
https://gyazo.com/f055e1a59b6500fac7d95d8a3a2a56d5

And one more question.
Is this changes are legal? Or i can get banned for this? If it illegal - i'll better wait for a new No-Bling from developer. If its legal - please edit my mistakes in gameinfoModified.gi

**Comment by Wolf49406** [comment]
@MadSochi like this
![image](https://user-images.githubusercontent.com/26302888/150062597-324f66c8-d53f-45fe-b9d7-94e440564889.png)
>Is this changes are legal
How can it not be? Dota will looks on CRC but CRC is ok. 
But you better use client.dll patch bc it's just completely turns this check off (always return true), it's way more safe.
Valve can change gaminfo in every second and your CRC will be wrong. And no, VAC never bother about dlls.
Otherwise, launching Dota would take as much time as checking the integrity of the game files.

**Comment by MadSochi** [comment]
@Wolf49406
if you are not busy now - can you join to call in Discord? MadSochi#0620

**Comment by Wolf49406** [comment]
@MadSochi as you may already notice my english is not that good to do conversation :roll_eyes: 
You better white [me](https://t.me/wolf49406) on TG if you have a questions.

**Comment by MadSochi** [comment]
@Wolf49406 are you Russian? I see your name in Russian. Александр Вульф. If yes - call me.

**Comment by Lgazana** [comment]
Hey, @Wolf49406

I just tried your method of patching the client. dll but I'm a n00b at this and I think it didn't work because I can launch the game and hit Find Match with no problems but no-bling isn't there and isn't working, if you could help me out and tell me what I did wrong, I'd be grateful!

So, like I said, I'm a total noob at this and have never used HxD before, but here's what I did:

1. I launched HxD and then Opened client.dll with it.
2. I press Ctrl+R and the replace window appears, so I select "Hex-values" and fill in the boxes as shown.
[https://i.imgur.com/0ttC6ol.png](url)
3. I pressed the OK button.
4. This is the end result.
[https://i.imgur.com/hWnc23z.png](url)
5. I save and launch Dota 2.

But no-bling isn't working; please let me know what I'm doing wrong here ;')

**Comment by MadSochi** [comment]
@Lgazana

Here is instruction to how get back NoBling to work.
ALL REGARDS AND THANKS GOES TO @Wolf49406 WHO PERSONALLY HELPED ME TO MAKE IT REAL !

1) Launch Hex Editor (like HxD Hex Editor)
Open file client.dll in directory
\Steam\steamapps\common\dota 2 beta\game\dota\bin\win64\

Press Ctrl+F and enter this simbols 44 38 67 39 74 39
When you found the line with that 44 38 67 39 74 39 then change 74 to EB and you will get this 44 38 67 39 EB 39
Save file.

2) Open file gameinfo.gi by Notepad++ programm.
File gameinfo.gi in directory
\Steam\steamapps\common\dota 2 beta\game\dota\
and
Change line 4
	// gameinfo.gi is the non-branch-varying content and can be integrated between branches.
to
	// gameinfo.gi is the non-

Change line 39 to
			Game				NoBling
and line 40 to
			Mod			 	    NoBling

It will looks like this:
			// *LANGUAGE* will be replaced with the actual language name. If not running a specific language, these paths will not be mounted
			Game_Language		dota_*LANGUAGE*
			Game				NoBling
			Mod			 	NoBling

			// These are optional low-violence paths. They will only get mounted if you're in a low-violence mode.
			Game_LowViolence	dota_lv
			
Save file gameinfo.gi

3) Create a new folder with name NoBling in directory
\Steam\steamapps\common\dota 2 beta\game

Copy your .vpk file to the folder
\Steam\steamapps\common\dota 2 beta\game\NoBling

your .vpk file created by NoBlink mod is in directory:
\Steam\steamapps\common\dota 2 beta\game\dota_tempcontent
and named pak01_dir.vpk

Now you can start Dota 2 and enjoy with NoBling functions.

**Comment by Lgazana** [comment]
Oh my goodness, it's working again!!! @MadSochi, thank you so much for your detailed instructions; I followed them and it worked!!
> ALL REGARDS AND THANKS GOES TO @Wolf49406 WHO PERSONALLY HELPED ME TO MAKE IT REAL !

True, many thanks to @Wolf49406!!

**Comment by Wolf49406** [comment]
Also you can just change the line 2086 (Ctrl+f > "dota_tempcontent") in NoBling's vpkmod.cs from
`string sourcefile = GAMEPATH + "/dota/pak01_dir.vpk", outputfile = GAMEPATH + "/dota_tempcontent/pak01_dir.vpk";`
to
`string sourcefile = GAMEPATH + "/dota/pak01_dir.vpk", outputfile = GAMEPATH + "/NoBling/pak01_dir.vpk";`

**Comment by Lgazana** [comment]
Niice, now i don't even have to worry about moving the vpk file to the correct folder each time it is generated.
@Wolf49406 Thanks again!
Also, I believe the launch option '-tempcontent' is no longer required, so I'll remove it for the time being ;P

**Comment by Wolf49406** [comment]
@Lgazana yup, actually -tempcontent [was completely removed](https://github.com/SteamDatabase/GameTracking-Dota2/commit/e793776d4038bc76f48779af9bf009db19d64247#diff-b14ae59d5038832206b3236b4a2e19936a4b0e6cc3402a59e326cf4a249a24cd).

**Comment by warden1437** [comment]
Did something wrong?
https://gyazo.com/8a5123bfcd3e71ebf4372b1e11831bbe

**Comment by Wolf49406** [comment]
@warden1437 obviously. Describe step by step what you did.
![image](https://user-images.githubusercontent.com/26302888/150154692-6fae95da-09c0-418f-8440-a8ac0cbc5fe9.png)

**Comment by warden1437** [comment]
@Wolf49406 Actually idk why but i did 2nd and 3rd step there, but couldnt do the 1st bc of that (2nd scrntsht) just cant found 44 38 67 39 74 39, mb i should reintstall dota?
https://gyazo.com/82f63c8930ca7727c498ce8c85d25e3e
https://gyazo.com/160304c8f19e0602134e0c0996a5d1e7

**Comment by Wolf49406** [comment]
@warden1437 Are you sure you're on the right tab?
(no idea how to change the interface language here, lmao)
![image](https://user-images.githubusercontent.com/26302888/150157221-728f307a-bc32-410f-b9cb-044e4a3ab6e9.png)

**Comment by warden1437** [comment]
А если по русски, то у меня даже окно не такое, я мб прогу не ту юзаю?) 
@Wolf49406

**Comment by warden1437** [comment]
@Wolf49406 нашел Hex значения, изменил на eb, помогло похоже

**Comment by Wolf49406** [comment]
For anyone who don't want to messing with manual patching, you can use [my new patcher](https://github.com/Wolf49406/Dota2Patcher).

**Comment by hode69** [comment]
> For anyone who don't want to messing with manual patching, you can use [my new patcher](https://github.com/Wolf49406/Dota2Patcher).

they said it is for bypassing the VAC a.k.a reviving the NoBling, but is this safe from VAC Ban? i mean it looks like some cheat advantage there. tbh i don't want to use cheats, i just want to modding my skin so i won't get bored.

**Comment by Wolf49406** [comment]
> @Wolf49406 they said it is for bypassing the VAC a.k.a reviving the NoBling, but is this safe from VAC Ban? i mean it looks like some cheat advantage there. tbh i don't want to use cheats, i just want to modding my skin so i won't get bored.

https://github.com/No-Bling/DOTA/issues/76#issuecomment-1014974809
https://github.com/Wolf49406/Dota2Patcher/issues/2#issuecomment-1015022295

Also it's not about bypassing VAC. Valve just too lazy to make new pop-up.

**Comment by robbyz512** [comment]
> @robbyz512 hey man u have been away from ur discord for a long time are you doing ok? how is the mods going?
I still work on dota mods for myself and friends but I'm not working on the desktop app anymore, I doubt the average user would trust using it, and now that valve is giving warnings for custom vpks sooner or later one of dotas updates would give my users game file modification warnings and they'd just uninstall it.

**Comment by rohit-rcrohit7** [comment]
Hi @Wolf49406 Does the hex value change still work? 
Trying to just use harmless dotamods skins.

**Comment by rohit-rcrohit7** [comment]
![image](https://user-images.githubusercontent.com/19775822/187650615-3be44540-4b98-4aad-b0c1-728fb6022afe.png)
the .dll file has changed since I believe from inspecting through IDA

**Comment by MadSochi** [comment]
AveYo ! My Dear ! My saver ! Maybe my love (just joke).
I'm tired of play Dota 2 with so many new skins FOR YEARS !
I've used your mod to get back DEFAULT Dota 2 for years. But it's in the past for now.
Please tell me. Do we have a solution somewhere inside the global web to get back DEFAULT Dota 2 skins in 2024?

Maybe some of Dota2skinChangers can do it? Maybe you'll be back and make update of your beautiful NO-BLING?
Please. Answer. I'm calling you.
My Discord nickname is MadSochi (if you wish to talk inside Discord).

**Comment by Wolf49406** [comment]
@MadSochi https://github.com/robbyz512/dota2-minify
