### ISSUE TITLE
16.01.2022 valve killed this beautiful mod

### ISSUE THREAD

**Issue by MadSochi** [No-Bling/DOTA#77]
I've used this mod for YEARS !
I'm so happy when i can NOT to see any visual changes of heroes.
I'm so happy when i can NOT to hear any YELLing from players like "lakad matataq" or "MMR is just a number" !

I'm so happy when everything in dota 2 is just STANDART and DEFAULT.
When i don't need when i see a new visual on some hero first seconds thinks WHO IS IT !

I'm playing DotA about 18 years from DotA 1. And when i found NO BLING - it was like my dreams comes true.

No chat YELLing. No visuals. Everything is the SAME in every new match. So beautiful !

So BIG RESPECT to developer of NO BLING !

Please find the way to get it back my dear developer.

**Comment by AveYo** [comment]
OK

**Comment by lordamir20132** [comment]
yeah they killed it any fix soon?
I cant wait for it
