### ISSUE TITLE
new fix?

### ISSUE THREAD

**Issue by sfyyeah** [No-Bling/DOTA#80]
no

**Comment by paxakamac** [comment]
was trawling through that russian guy's code(thank you higher ed in computer science that i'm using for a dead end job!) and the new pattern is 80 3D 53 2D 31 02, the 74 39 right before 80 should be changed to EB 39

**Comment by rektmeme01** [comment]
> was trawling through that russian guy's code(thank you higher ed in computer science that i'm using for a dead end job!) and the new pattern is 80 3D 53 2D 31 02, the 74 39 right before 80 should be changed to EB 39

thank you for this!!
