### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by yvnglayer** [No-Bling/DOTA#82]
Hi, when will the dota nobling update be released?

**Comment by AveYo** [comment]
On the 29th

Now seriously, I am infrequently working on it. 
_Whenever I get back to DOTA, the universe is telling me to stay away. 
If it's not the cancer, it's covid + flu combo pinning me down for 6 freaking weeks.
All good now. Promised an update in the winter. Did not specify which winter.
It is still winter over here._

On the technical aspect of it, I can no longer use `items_game.txt` in -language based mod, 
without VAC dangerous dll patching or hash collision for config files. 
But no worries, old-fashioned resource-replacements still works fine.
Disabling taunts has proven a bit difficult to disable - more and more are bundled in the hero model file, behind custom compression format with preloading.
I have finally worked out the format and an automatic method of patching the taunts, so it won't take much longer. Hopefully. Pray for me.

**Comment by yvnglayer** [comment]
Thanks, I'll wait, I'm very glad to hear that you didn't abandon the project, get well soon <3 @AveYo

**Comment by VP123445** [comment]
> Thanks, I'll wait, I'm very glad to hear that you didn't abandon the project, get well soon <3 @AveYo

does it work now? how to fix it correctly?

**Comment by lordamir20132** [comment]
I have a question
Im using a bat file with these launch options
something makes my game freeze in middle of match sometimes
does anyone know which one should i remove to fix my problem?
 -high -nobreakpad  -novr -nojoy -disablehangwatchdog -noloaderlockprobe  -dx11renderthreadstack  -mainthreadpriority 1 -novid -mapdota -tempcontent -forcepow2dxt -maxtextureres 256 -oldtexturestreaming -swap_chain_as_is +fps_max[0] -noaafonts -nofocus -novr -nohltv -nojoy -uselocalweb -disablehangwatchdog -condebug -conclearlog +map_enable_background_maps 0 -onethreadpool -threads 4 -disallowhwmorph
 its all my launch options

**Comment by AveYo** [comment]
holly cow that's everything just stuffed in there for good measure 
historically, `-high` will cause freezes if the system is not 100% stable or there's concurrent cpu usage. you're also using `-mainthreadpriority 1` which is like above high 
-threads is a big no-no (never personally recommended it)  

remove all of them, and maybe keep `-novid` `-forcepow2dxt` `-disallowhwmorph` `-maxtextureres 256` `-oldtexturestreaming` `-swap_chain_as_is` `+map_enable_background_maps 0` if you're on a potato

**Comment by lordamir20132** [comment]
@AveYo thanks you 
I removed mainthreadpriority 1 i think its ok now
when my game crashes the screen gets stuck but the sounds keeps playing normally
I highly suggest you make a discord channel for your small community we love your work if it wasn't for your mod i would quit dota after removing direct x9

**Comment by WishmasterZero** [comment]
> does it work now? how to fix it correctly?

Use this patcher https://github.com/Wolf49406/Dota2Patcher
After that run nobling mod.
Add -tempcontent to Dota launch options.

Open file gameinfo.gi by Notepad++ programm.
File gameinfo.gi is in directory
\Steam\steamapps\common\dota 2 beta\game\dota
and
Change line 39 to
Game dota_tempcontent
and line 40 to
Mod dota_tempcontent

Don't forget to save changes.

It should work then.

**Comment by sfyyeah** [comment]
> 

WORKING, THX<3

**Comment by KaeLL** [comment]
@WishmasterZero VAC: hmm, interesting.

**Comment by yvnglayer** [comment]
waiting room 🚀

**Comment by gnatdagnat** [comment]
@WishmasterZero Hi, is Wolf49406's patcher being updated for this?? Cause it seemed like the required changes are different now than when he first put that out. I'm following instructions to the letter and it's not working for me, so I thought Valve broke it again and we needed new bytes to patch in client.dll. If it's something else I'm doing I would love to get it working - is "-language tempcontent" correct for launch options, by the way?

**Comment by WishmasterZero** [comment]
@gnatdagnat It's just -tempcontent
It might stop working after dota updates. You just revert patch and then apply it again and it works.

**Comment by gnatdagnat** [comment]
> @gnatdagnat It's just -tempcontent It might stop working after dota updates. You just revert patch and then apply it again and it works.

I'm pretty sure -tempcontent does nothing now. I believe it was AveYo who said in another issue thread that -tempcontent has been completely removed by Valve so that shouldn't be the solution. Plus I have tried it anyway and it did not fix.
I've been attempting reverting/applying patch, verifying game files and re-editing my gameinfo.gi, etc and nothing gets no-bling working. Which sucks. I don't know what could be wrong.
Thanks for the input though.

**Comment by WishmasterZero** [comment]
@gnatdagnat When you edited gameinfo file, did you click on save icon in Notepad++ It doesn't save automatically if you just close it. And use -tempcontent 
Step 1. download https://github.com/Wolf49406/Dota2Patcher/releases/latest and run it. Choose either option 1 or 4
Step 2. run No-Bling-builder.bat
Step 3. Add lines to gameinfo.gi file in \Steam\steamapps\common\dota 2 beta\game\dota using Notepad++
line 39 
Game dota_tempcontent
and line 40 
Mod dota_tempcontent
**Be sure to save changes there's save icon at the top left.**

Step 4. add -tempcontent to dota launch options.

**Comment by gnatdagnat** [comment]
@WishmasterZero 
This is a bit embarrassing - I was looking at my Phoenix every time I tested it, which should be fine as I have some immortals on that hero which should be changed by no-bling, but it seems like some of the effects are just not being turned off properly. After looking at several other heroes it looks like the mod is functioning.
I was in fact doing everything right, including saving my gameinfo edit - I use n++ all the time.... But I'm just an idiot, so thanks for your help! I'm glad to know the community can keep the mod working even without the big patch from developer :)

**Comment by dotanohatsenjoyer** [comment]
@AveYo Any updates, master?

**Comment by ani917** [comment]
when update?

**Comment by sonhador93** [comment]
когда обновление?

**Comment by UpdateNoBlingPlease** [comment]
> On the 29th
> 
> Now seriously, I am infrequently working on it. _Whenever I get back to DOTA, the universe is telling me to stay away. If it's not the cancer, it's covid + flu combo pinning me down for 6 freaking weeks. All good now. Promised an update in the winter. Did not specify which winter. It is still winter over here._
> 
> On the technical aspect of it, I can no longer use `items_game.txt` in -language based mod, without VAC dangerous dll patching or hash collision for config files. But no worries, old-fashioned resource-replacements still works fine. Disabling taunts has proven a bit difficult to disable - more and more are bundled in the hero model file, behind custom compression format with preloading. I have finally worked out the format and an automatic method of patching the taunts, so it won't take much longer. Hopefully. Pray for me.

Hey mate, what's going on with this update? I see that you're active on GitHub and also see people trying to make other download a cheat tool to make the necessary changes for NoBling to work.

There are a lot of people who depend on NoBling to enjoy Dota 2, so could you please push an update for this beloved mode, and make our day. I would really appreciate it.
