### ISSUE TITLE
anyone knows?

### ISSUE THREAD

**Issue by ryouik1** [No-Bling/DOTA#83]
How to leave the changed icons of skills from immortals / arcana, as it was in previous versions of nobling. There you could leave the changed skill icons and remove the particles. I would really like to know how to do it.

**Comment by robbyz512** [comment]
I'd just replace the default icon with the one you want, for example the arcana blur.

rename `pa_fall20_immortal_blur_png.vtex_c` to `phantom_assassin_blur_png.vtex_c`

then put it in this path and build vpk

`panorama\images\spellicons\phantom_assassin\ravening_ability_icons\phantom_assassin_blur_png.vtex_c`

**Comment by ryouik1** [comment]
> I'd just replace the default icon with the one you want, for example the arcana blur.
> 
> rename `pa_fall20_immortal_blur_png.vtex_c` to `phantom_assassin_blur_png.vtex_c`
> 
> then put it in this path and build vpk
> 
> `panorama\images\spellicons\phantom_assassin\ravening_ability_icons\phantom_assassin_blur_png.vtex_c`

I don't have a spellicons folder in panorama\images...
what should i do?
