### ISSUE TITLE
Unable to run No-Bling anymore

### ISSUE THREAD

**Issue by ZzZombo** [No-Bling/DOTA#84]
Hello! Recently I've added a new storage medium into my system and moved Steam onto it. However, I kept DotA 2 on the old drive, *and changed its drive letter* (the new drive essentially takes over the old). Since then I'm unable to use this program because it fails to find either the Steam folder or the game. How do I proceed?

**Comment by ani917** [comment]
> 

https://github.com/No-Bling/DOTA/issues/79#issuecomment-1023440716
