### ISSUE TITLE
AveYo, please update NoBling

### ISSUE THREAD

**Issue by UpdateNoBlingPlease** [No-Bling/DOTA#86]
I've gone through the recent threads and saw AveYo mentioning that he had a fix ready-to-go, but he never updated the mod. I don't want to download other weird software to edit dlls to make NoBling work again.

Can we please have an official fix for this beloved mode AveYo?

**Comment by robbyz512** [comment]
I created my own mod tool if you want to use that check out my profile.
Anyway, you are going to have to patch gameinfo one way or another to load VPK mods. You can do it manually yourself with a hex editor if you don't want to use dota2patcher.

**Comment by Splozy** [comment]
Yeah it would be nice, especially just to stop these guys advertising their hacks in these threads

**Comment by robbyz512** [comment]
> Yeah it would be nice, especially just to stop these guys advertising their hacks in these threads

![43c](https://user-images.githubusercontent.com/48497779/189350453-e3433944-3509-4cde-90a4-6e0917b946fb.png)

**Comment by ani917** [comment]
need update
