### ISSUE TITLE
Dont working for immortal skills and abilities 

### ISSUE THREAD

**Issue by Rainknee** [No-Bling/DOTA#9]
Dont working for a skills like sunstrike (magus apex) , pounce with immortal swords on slark , and many other. I want to have default animations with this items on hero , why it dont work? ;C
Pls help me, maybe i am doing something wrong or?

**Comment by AveYo** [comment]
Abilities category might have suffered a set-back. Will investigate it tomorrow.  
Thanks for reporting it!

**Comment by Rainknee** [comment]
![1](https://user-images.githubusercontent.com/49289570/55642752-0cc16a00-57da-11e9-96fa-52120e370325.png)
Yeah , now working , big thanks to you! :) 
Your mod is really helping me to play more comfortable during the battles

**Comment by AveYo** [comment]
Great. Did you also test the PMS option? (pre-made named _ ) it should revert hats completely (\\_/)

**Comment by Rainknee** [comment]
yea , i tried all , but i guess with my laptop i dont need menu and pms options  :)
